### ISSUE TITLE
[BUG] app stops recording video (but keeps recording audio) after switching to any other app or turning the screen off

### ISSUE THREAD

**Issue by Kyndansky** [anonfaded/FadCam#76]
### Steps to Reproduce
1. Open the app
2. Click on the 'play' button
3. change app/go to home screen/turn off the screen
4. app stops recording video

### Expected Behavior
Apps keeps recording properly

### Actual Behavior
App stops recording video.
the microphone permission icon in the top right of my notification bar appears but the camera permission icon disappears as soon as i switch to other apps, go back to home screen or turn off the screen.
the video still gets recorded and when i try to open the app again i stops. the video output is a normal video that includes what i recorded before switching app/turning screen off + the last frame of recording which lasts until the video is actually stopped (which happens when i try to open the app again).

### Device information
- **Device:** : Redmi Note 12 Pro 4G
- **OS:** Android 13
- **App Version:** 1.2.1-beta

### Priority
- [x] High

**Comment by anonfaded** [comment]
Oh this issue was fixed way before and we tested on so many devices, users also confirmed that it got fixed, still you are facing this which is very weird. Like here recently someone was facing similar issue and he was using the old version from F-Droid i guess: https://github.com/anonfaded/FadCam/issues/72

Just to confirm, when you installed the app, you  gave permission to allow to 'disable battery optimization'? And you mentioned you are using the latest beta version from GitHub so this should work normally tho as we have fixed all the bugs that were causing this. Also what about the persistent notification, was it there in notification panel showing message that 'Recording in progress'?

**Comment by Kyndansky** [comment]
> Oh this issue was fixed way before and we tested on so many devices, users also confirmed that it got fixed, still you are facing this which is very weird. Like here recently someone was facing similar issue and he was using the old version from F-Droid i guess: #72
> 
> Just to confirm, when you installed the app, you gave permission to allow to 'disable battery optimization'? And you mentioned you are using the latest beta version from GitHub so this should work normally tho as we have fixed all the bugs that were causing this. Also what about the persistent notification, was it there in notification panel showing message that 'Recording in progress'?

i'm sure i installed the right version from github since i had installed the old F-Droid one and then switched to the github version to see if that would've worked. i disabled the battery optimization setting. the persistent notification only appears when i'm in the app. when i switch to other apps the camera persistent notification disappears, while the microphone one remains.
it is very weird because i can't find anyone else who has this problem. i have tried another app just to see if it's my phone's problem or fadcam's and the other app works just fine. i also tried experimenting here and there with any setting that could prevent the app from working properly but i had no luck

**Comment by anonfaded** [comment]
I would suggest to delete the app and reinstall the universal build from here: https://github.com/anonfaded/FadCam/releases/tag/v1.2.1-beta

Maybe you downloaded the armeabi or arm64 version and one of them wasn't compatible with your phone? Universal has all the builds together that's why its size is also bulky but it may work.

And i mean this notification, not that green dot that appears at top right:

![Screenshot_20241216-021327.jpg](https://github.com/user-attachments/assets/f2b6cb5c-9f01-4e47-a032-81ec68213a04)

Let me know if it works then.

**Comment by Kyndansky** [comment]
> I would suggest to delete the app and reinstall the universal build from here: https://github.com/anonfaded/FadCam/releases/tag/v1.2.1-beta
> 
> Maybe you downloaded the armeabi or arm64 version and one of them wasn't compatible with your phone? Universal has all the builds together that's why its size is also bulky but it may work.
> 
> And i mean this notification, not that green dot that appears at top right:
> 
> ![Screenshot_20241216-021327.jpg](https://github.com/user-attachments/assets/f2b6cb5c-9f01-4e47-a032-81ec68213a04)
> 
> Let me know if it works then.

i re-installed the universal version (which i had already installed but i still uninstalled and re-installed just in case) and it still doesn't work. the persistent notification (thanks for the screenshot btw, i now understand which one it is) is present, and until i try to open the app again (which causes it to crash) that notification stays there.

**Comment by anonfaded** [comment]
I'll try to find the bug, and will sometime add a logs saving feature which hopefully will show the logs of why it crashed. This can take some time coz I'm these days busy.

Normally the app crash happens due to the Android's battery saving system which kills the app after some time, but still it records for around 30 minutes before killing the app, and in your case it directly stops the video. 

Also i would suggest to try the alternative apps like XSCamera to see if it also crashes or not. Finding the issue is hard without testing myself but I'll try to find. Thanks

**Comment by Kyndansky** [comment]
> I'll try to find the bug, and will sometime add a logs saving feature which hopefully will show the logs of why it crashed. This can take some time coz I'm these days busy.
> 
> Normally the app crash happens due to the Android's battery saving system which kills the app after some time, but still it records for around 30 minutes before killing the app, and in your case it directly stops the video. 
> 
> Also i would suggest to try the alternative apps like XSCamera to see if it also crashes or not. Finding the issue is hard without testing myself but I'll try to find. Thanks

thanks for the effort you are putting in replying in such a short time. i'll try other apps for now. thanks again for trying to help.

**Comment by anonfaded** [comment]
> thanks for the effort you are putting in replying in such a short time. i'll try other apps for now. thanks again for trying to help.

Yeah no problem, made it for the community so need to try my best to solve the issues:)

**Comment by lawson85** [comment]
I would suggest looking at dontkillmyapp.com to prevent Android killing apps.

**Comment by lawson85** [comment]
You may be able to identify crashes with this: https://github.com/TacoTheDank/Scoop
